(function(root,factory){const api=factory(root||globalThis);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ProjectWorkSheet=api;})(typeof window!=='undefined'?window:globalThis,function(global){'use strict';
function arr(v){return Array.isArray(v)?v:[]}function txt(v){return String(v==null?'':v).trim()}function lower(v){return txt(v).toLowerCase()}function openTask(t){return !['erledigt','abgeschlossen','done'].includes(lower(t&&t.status));}
function employeeName(m){return txt(m&&(m.name||m.vorname&&((m.vorname||'')+' '+(m.nachname||''))||m.displayName||m.email))||'Mitarbeiter';}
function projectAddress(p){return txt(p&&(p.adresse||p.address||p.baustelle||p.ort));}
function taskEmployeeId(t){return txt(t&&(t.mitarbeiterId||t.mitarbeiterID||t.employeeId||t.assigneeId||t.zugewiesenAn||t.verantwortlichId));}
function taskEmployeeName(t){return txt(t&&(t.mitarbeiter||t.mitarbeiterName||t.assignee||t.verantwortlich));}
function employeesForProject(project){const state=global.S||{},tasks=arr(state.aufgaben).filter(t=>String(t.projektId||'')===String(project.id)&&openTask(t)),all=arr(state.mitarbeiter),ids=new Set(tasks.map(taskEmployeeId).filter(Boolean)),names=new Set(tasks.map(taskEmployeeName).filter(Boolean).map(lower));let out=all.filter(m=>ids.has(String(m.id))||names.has(lower(employeeName(m))));if(!out.length&&arr(project.team).length)out=all.filter(m=>arr(project.team).map(String).includes(String(m.id)));return out;}
function tasksFor(project,employee,mode){const state=global.S||{},eid=employee?String(employee.id||''):'',ename=employee?lower(employeeName(employee)):'';return arr(state.aufgaben).filter(t=>{if(String(t.projektId||'')!==String(project.id)||!openTask(t))return false;if(employee){const tid=taskEmployeeId(t),tn=lower(taskEmployeeName(t));if(tid&&eid&&tid!==eid)return false;if(!tid&&tn&&ename&&tn!==ename)return false;if((tid||tn)&&!((eid&&tid===eid)||(ename&&tn===ename)))return false;}if(mode==='today'){const due=txt(t.faellig||t.datum);if(due&&due>new Date().toISOString().slice(0,10))return false;}return true;});}
function pdf(project,employee,mode){const tasks=tasksFor(project,employee,mode);if(typeof global.pdfNewDoc!=='function'||typeof global.saveOrSharePdf!=='function'){global.toast?.('PDF-Funktion nicht verfügbar.','error');return false;}const doc=global.pdfNewDoc();let y=global.pdfHeader?global.pdfHeader(doc,'Arbeitszettel'):20;const write=(s,bold)=>{if(global.pdfWriteWrapped)y=global.pdfWriteWrapped(doc,s,15,y,180)+2;else{doc.text(s,15,y);y+=7;}};write('Mitarbeiter: '+(employee?employeeName(employee):'________________________'));write('Datum: '+new Date().toLocaleDateString('de-DE'));write('Projekt: '+txt(project.name||project.titel||'Projekt'));if(projectAddress(project))write('Baustelle: '+projectAddress(project));write(' ');write(mode==='today'?'Aufgaben heute':'Offene Aufgaben im Projekt');if(!tasks.length)write('Keine offenen zugeordneten Aufgaben.');tasks.forEach((t,i)=>{write('☐ '+(i+1)+'. '+txt(t.titel||t.name||t.beschreibung||'Aufgabe'));const meta=[t.prioritaet&&('Priorität: '+t.prioritaet),t.faellig&&('Termin: '+t.faellig),t.notiz||t.bemerkung].filter(Boolean).join(' · ');if(meta)write('   '+meta);});write(' ');write('Material / fehlt: ______________________________________________');write('Bemerkungen: _________________________________________________');write('Arbeitszeit: __________ bis __________');write('Unterschrift Mitarbeiter: _____________________________________');global.pdfFooter?.(doc);const safe=employee?employeeName(employee).replace(/[^a-z0-9_-]+/gi,'_'):'Mitarbeiter';global.saveOrSharePdf(doc,'Arbeitszettel_'+safe+'_'+new Date().toISOString().slice(0,10)+'.pdf');return true;}
function open(project){if(!project||typeof global.openModal!=='function')return false;const employees=employeesForProject(project);global.openModal('<div class="modalHead"><div><div class="modalTitle">Arbeitszettel drucken</div><div class="pageSub">Offene Projektaufgaben als Mitarbeiter-PDF.</div></div><button class="iconBtn" onclick="closeModal()">×</button></div><div class="formRow"><label>Mitarbeiter</label><select id="pwsEmployee"><option value="">Nicht festlegen</option>'+employees.map(m=>'<option value="'+String(m.id).replace(/"/g,'&quot;')+'">'+employeeName(m).replace(/</g,'&lt;')+'</option>').join('')+'</select></div><div class="formRow"><label>Umfang</label><select id="pwsMode"><option value="today">Heute</option><option value="project">Alle offenen Aufgaben im Projekt</option></select></div><div class="modalFoot"><button class="btn" onclick="closeModal()">Abbrechen</button><button id="pwsPrint" class="btn primary">PDF / Drucken</button></div>');global.document.getElementById('pwsPrint')?.addEventListener('click',()=>{const id=global.document.getElementById('pwsEmployee')?.value||'',employee=arr(global.S&&global.S.mitarbeiter).find(m=>String(m.id)===String(id))||null,mode=global.document.getElementById('pwsMode')?.value||'today';pdf(project,employee,mode);});return true;}
return{employeeName,taskEmployeeId,employeesForProject,tasksFor,pdf,open};});
