(function(root,factory){const api=factory(root||globalThis);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ProjectQuickActions=api;if(root&&root.document)api.install();})(typeof window!=='undefined'?window:globalThis,function(global){'use strict';
function parseProjectHash(hash){const p=String(hash||'').replace(/^#/,'').split('/').filter(Boolean);return p[0]==='projekte'&&p[1]?{projectId:decodeURIComponent(p[1]),tab:p[2]||'uebersicht'}:null;}
function make(tag,cls,text){const el=global.document.createElement(tag);if(cls)el.className=cls;if(text!=null)el.textContent=text;return el;}
function project(){const ctx=parseProjectHash(global.location&&global.location.hash);const list=global.S&&Array.isArray(global.S.projekte)?global.S.projekte:[];return ctx?list.find(x=>String(x.id)===String(ctx.projectId))||null:null;}
function go(hash){if(typeof global.goTo==='function')global.goTo(hash);else global.location.hash=hash;}
function openProjectTask(projectId){go('#aufgaben');let attempts=0;const tryOpen=()=>{attempts++;const doc=global.document;if(!doc)return;let select=doc.getElementById('agProjekt');if(!select){const head=doc.querySelector('#view .pageHead');const candidates=head?Array.from(head.querySelectorAll('.btn')):[];const create=candidates.find(b=>/aufgabe|neu|erstellen|anlegen/i.test(String(b.textContent||''))&&!b.classList.contains('danger'));if(create)create.click();select=doc.getElementById('agProjekt');}if(select){select.value=String(projectId);select.dispatchEvent(new global.Event('change',{bubbles:true}));const title=doc.getElementById('agTitel');if(title)title.focus();return;}if(attempts<8)global.setTimeout(tryOpen,40);};global.setTimeout(tryOpen,0);}
function action(label,kind,fn){const b=make('button','btn projectQuickAction '+(kind||''),label);b.type='button';b.addEventListener('click',fn);return b;}
function openActionMenu(p){if(!p||typeof global.openModal!=='function')return false;const field=global.ProjectFieldOps;const pid=encodeURIComponent(p.id);global.openModal('<div class="modalHead"><div><div class="modalTitle">Neu in diesem Projekt</div><div class="pageSub">Die häufigsten Baustellenaktionen an einer Stelle.</div></div><button class="iconBtn" onclick="closeModal()">×</button></div><div id="projectActionGrid" class="projectActionGrid"></div>');const grid=global.document.getElementById('projectActionGrid');if(!grid)return false;const item=(title,sub,fn)=>{const b=make('button','projectActionMenuItem');b.type='button';b.appendChild(make('strong','',title));b.appendChild(make('span','',sub));b.addEventListener('click',()=>{global.closeModal?.();fn();});grid.appendChild(b);};item('Aufgabe','Projekt ist automatisch vorbelegt',()=>openProjectTask(p.id));item('Beleg / Ausgabe','Foto aufnehmen und Kosten zuordnen',()=>go('#projekte/'+pid+'/material'));item('Baustellenfoto','Foto dokumentieren und kategorisieren',()=>field?.openPhotoForm?.(p,'Baustelle'));item('Mangel','Foto, Frist und Verantwortlichen erfassen',()=>field?.openDefectForm?.(p));item('Tagesbericht','Arbeiten, Personen, Stunden und Notizen',()=>field?.openDailyReportForm?.(p));item('Aufmaß','Ausgeführte Mengen erfassen',()=>go('#projekte/'+pid+'/aufmass'));item('Nachtrag','Zusatzleistung dokumentieren',()=>go('#projekte/'+pid+'/nachtraege'));item('Dokumente','Projektunterlagen öffnen',()=>go('#projekte/'+pid+'/dokumente'));return true;}
function enhance(){if(!global.document)return false;const ctx=parseProjectHash(global.location&&global.location.hash),p=project();if(!ctx||!p)return false;const view=global.document.getElementById('view'),head=view&&view.querySelector('.pageHead');if(!head)return false;let bar=view.querySelector('[data-project-quick-actions="1"]');const signature=String(p.id)+'|'+ctx.tab;if(bar&&bar.dataset.signature===signature)return true;if(bar)bar.remove();bar=make('section','projectQuickActions');bar.dataset.projectQuickActions='1';bar.dataset.signature=signature;const intro=make('div','projectQuickActionsIntro');intro.appendChild(make('span','projectQuickActionsLabel','Direkt im Projekt'));intro.appendChild(make('strong','',String(p.name||p.titel||'Projekt')));bar.appendChild(intro);const buttons=make('div','projectQuickActionsButtons');buttons.appendChild(action('+ Neu','primary',()=>openActionMenu(p)));buttons.appendChild(action('+ Aufgabe','',()=>openProjectTask(p.id)));buttons.appendChild(action('Beleg','',()=>go('#projekte/'+encodeURIComponent(p.id)+'/material')));buttons.appendChild(action('Aufmaß','',()=>go('#projekte/'+encodeURIComponent(p.id)+'/aufmass')));bar.appendChild(buttons);head.insertAdjacentElement('afterend',bar);return true;}
let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;Promise.resolve().then(()=>{scheduled=false;enhance();});}
function install(){if(!global.document)return false;enhance();global.addEventListener?.('hashchange',schedule);const view=global.document.getElementById('view');if(view&&typeof global.MutationObserver==='function'){const observer=new global.MutationObserver(records=>{if(records.some(r=>r.type==='childList'&&Array.from(r.addedNodes||[]).some(n=>n&&n.nodeType===1&&!n.closest?.('[data-project-quick-actions="1"]'))))schedule();});observer.observe(view,{childList:true,subtree:true});}return true;}
return{parseProjectHash,openProjectTask,openActionMenu,enhance,install};});
