(function(root,factory){
  const api=factory(root||globalThis);
  if(typeof module==='object'&&module.exports) module.exports=api;
  if(root) root.ProjectMeasurement=api;
  if(root&&root.document) api.install();
})(typeof window!=='undefined'?window:globalThis,function(global){
  'use strict';
  function n(v){const x=Number(v);return Number.isFinite(x)?x:0;}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function today(){return new Date().toISOString().slice(0,10);}
  function parseProjectHash(hash){const p=String(hash||'').replace(/^#/,'').split('/').filter(Boolean);return p[0]==='projekte'&&p[1]?{projectId:decodeURIComponent(p[1]),tab:p[2]||'uebersicht'}:null;}
  function projectById(id){const s=global.S;return s&&Array.isArray(s.projekte)?s.projekte.find(p=>String(p.id)===String(id))||null:null;}
  function measurements(project){return Array.isArray(project&&project.aufmasse)?project.aufmasse:[];}
  function materialById(project,id){return (Array.isArray(project&&project.material)?project.material:[]).find(m=>String(m.id)===String(id))||null;}
  function unitSales(m){return n(m&&m.verkaufspreis!=null?m.verkaufspreis:m&&m.preis);}
  function unitCost(m){return n(m&&m.einkaufspreis)+n(m&&m.subunternehmerPreis);}
  function quantity(m){return n(m&&m.menge);}
  function measuredQuantity(project,materialId){return measurements(project).filter(x=>String(x.materialId)===String(materialId)).reduce((s,x)=>s+n(x.menge),0);}
  function positionActual(project,m){const soll=quantity(m),ist=measuredQuantity(project,m.id),vk=unitSales(m),cost=unitCost(m),value=ist*vk,actualCost=ist*cost,db=value-actualCost;return {soll,ist,rest:Math.max(0,soll-ist),progress:soll>0?ist/soll*100:0,value,actualCost,db,margin:value>0?db/value*100:0};}
  function projectActual(project){return (project.material||[]).reduce((a,m)=>{const x=positionActual(project,m);a.sollValue+=quantity(m)*unitSales(m);a.istValue+=x.value;a.actualCost+=x.actualCost;a.db+=x.db;return a;},{sollValue:0,istValue:0,actualCost:0,db:0});}
  function money(v){try{return typeof global.fmtCurrency==='function'?global.fmtCurrency(n(v)):new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n(v));}catch(_){return n(v).toFixed(2)+' €';}}
  function save(){try{global.saveState?.();}catch(_){} }
  function refresh(){try{global.route?.(global.location.hash);}catch(_){enhance();}}
  function addMeasurement(project){const materialId=global.document.getElementById('pmMaterial')?.value||'';const m=materialById(project,materialId);if(!m){global.toast?.('Bitte eine LV-Position auswählen.','warn');return false;}const menge=n(global.document.getElementById('pmQty')?.value);if(menge<=0){global.toast?.('Bitte eine ausgeführte Menge größer 0 eingeben.','warn');return false;}if(!Array.isArray(project.aufmasse))project.aufmasse=[];project.aufmasse.push({id:typeof global.uid==='function'?global.uid():'am_'+Date.now(),materialId,menge,datum:global.document.getElementById('pmDate')?.value||today(),notiz:String(global.document.getElementById('pmNote')?.value||'').trim(),erstelltAm:new Date().toISOString()});save();refresh();global.toast?.('Aufmaß gespeichert.','success');return true;}
  function removeMeasurement(project,id){project.aufmasse=measurements(project).filter(x=>String(x.id)!==String(id));save();refresh();return true;}
  function summary(project){const a=projectActual(project);return '<div class="projectMeasurementSummary"><div><span>LV Soll</span><strong>'+esc(money(a.sollValue))+'</strong></div><div><span>Ausgeführt</span><strong>'+esc(money(a.istValue))+'</strong></div><div><span>Ist-Kosten aus LV</span><strong>'+esc(money(a.actualCost))+'</strong></div><div><span>DB ausgeführt</span><strong>'+esc(money(a.db))+'</strong></div></div>';}
  function render(project,body){const mats=project.material||[];body.innerHTML='<div class="projectMeasurementPage"><div class="pageHead"><div><div class="pageTitle">Aufmaß & Soll/Ist</div><div class="pageSub">Ausgeführte Mengen direkt den LV-Positionen zuordnen. Keine Rechnungserstellung.</div></div></div>'+summary(project)+'<div class="card projectMeasurementForm"><b>Aufmaß erfassen</b><div class="grid cols-2" style="margin-top:14px"><div class="formRow"><label>LV-Position</label><select id="pmMaterial"><option value="">Bitte wählen</option>'+mats.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.bezeichnung||m.titel||'Position')+' · Soll '+esc(m.menge||0)+' '+esc(m.einheit||'')+'</option>').join('')+'</select></div><div class="formRow"><label>Ausgeführte Menge</label><input id="pmQty" type="number" min="0" step="0.01"></div><div class="formRow"><label>Datum</label><input id="pmDate" type="date" value="'+today()+'"></div><div class="formRow"><label>Notiz</label><input id="pmNote" type="text" placeholder="Bereich, Etage, Besonderheit …"></div></div><button class="btn primary" id="pmAdd">Aufmaß speichern</button></div><div class="card"><div class="tableWrap"><table><thead><tr><th>LV-Position</th><th>Soll</th><th>Ist</th><th>Rest</th><th>VK Ist</th><th>Kosten Ist</th><th>DB</th></tr></thead><tbody>'+mats.map(m=>{const x=positionActual(project,m);return '<tr><td><b>'+esc(m.bezeichnung||m.titel||'Position')+'</b><div class="pageSub">'+esc(x.progress.toFixed(1).replace('.',','))+' % ausgeführt</div></td><td>'+esc(x.soll)+' '+esc(m.einheit||'')+'</td><td>'+esc(x.ist)+' '+esc(m.einheit||'')+'</td><td>'+esc(x.rest)+' '+esc(m.einheit||'')+'</td><td>'+esc(money(x.value))+'</td><td>'+esc(money(x.actualCost))+'</td><td>'+esc(money(x.db))+'<div class="pageSub">'+esc(x.margin.toFixed(1).replace('.',','))+' %</div></td></tr>';}).join('')+(mats.length?'':'<tr><td colspan="7"><div class="empty">Bitte zuerst LV-Positionen anlegen.</div></td></tr>')+'</tbody></table></div></div><div class="card"><b>Aufmaß-Historie</b><div class="tableWrap" style="margin-top:12px"><table><thead><tr><th>Datum</th><th>Position</th><th>Menge</th><th>Notiz</th><th></th></tr></thead><tbody>'+measurements(project).slice().reverse().map(x=>{const m=materialById(project,x.materialId);return '<tr><td>'+esc(x.datum)+'</td><td>'+esc(m&&(m.bezeichnung||m.titel)||'Position entfernt')+'</td><td>'+esc(x.menge)+' '+esc(m&&m.einheit||'')+'</td><td>'+esc(x.notiz||'–')+'</td><td><button class="iconBtn" data-pm-delete="'+esc(x.id)+'">🗑️</button></td></tr>';}).join('')+(measurements(project).length?'':'<tr><td colspan="5"><div class="empty">Noch kein Aufmaß erfasst.</div></td></tr>')+'</tbody></table></div></div></div>';global.document.getElementById('pmAdd')?.addEventListener('click',()=>addMeasurement(project));body.querySelectorAll('[data-pm-delete]').forEach(b=>b.addEventListener('click',()=>removeMeasurement(project,b.dataset.pmDelete)));return true;}
  function enhance(){const s=parseProjectHash(global.location&&global.location.hash);if(!s||s.tab!=='aufmass')return false;const p=projectById(s.projectId),body=global.document&&global.document.getElementById('projektTabBody');return p&&body?render(p,body):false;}
  function loadStyles(){if(!global.document||global.document.getElementById('projectMeasurementStyles'))return;const l=global.document.createElement('link');l.id='projectMeasurementStyles';l.rel='stylesheet';l.href='./src/modules/projects/projectMeasurement.css';global.document.head.appendChild(l);}
  let observer=null;function install(){loadStyles();enhance();if(typeof global.MutationObserver==='function'&&global.document){const view=global.document.getElementById('view');if(view){observer=new global.MutationObserver(()=>Promise.resolve().then(enhance));observer.observe(view,{childList:true,subtree:true});}}global.addEventListener?.('hashchange',()=>Promise.resolve().then(enhance));return true;}
  return {n,parseProjectHash,measurements,materialById,unitSales,unitCost,measuredQuantity,positionActual,projectActual,addMeasurement,removeMeasurement,render,enhance,install};
});
