(function(root,factory){const api=factory(root||globalThis);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ProjectCloseout=api;})(typeof window!=='undefined'?window:globalThis,function(global){'use strict';
function tasks(project){const s=global.S;return s&&Array.isArray(s.aufgaben)?s.aufgaben.filter(x=>String(x.projektId||'')===String(project.id)):[];}
function list(v){return Array.isArray(v)?v:[];}
function doneStatus(v){return ['erledigt','abgeschlossen','fertig'].includes(String(v||'').toLowerCase());}
function check(project){const openTasks=tasks(project).filter(x=>!doneStatus(x.status)).length;const openDefects=list(project.maengel).filter(x=>!doneStatus(x.status)).length;const photos=list(project.fotos).length;const reports=list(project.tagesberichte).length;const measurements=list(project.aufmasse).length;const draftChanges=list(project.nachtraege).filter(x=>String(x.status||'').toLowerCase()==='entwurf').length;const acceptance=project.abnahme||{};const acceptanceDone=String(acceptance.status||'').toLowerCase().startsWith('abgenommen')&&!!acceptance.unterschrift;const items=[
{key:'tasks',label:'Aufgaben abgeschlossen',ok:openTasks===0,detail:openTasks?openTasks+' offen':'Keine offenen Aufgaben'},
{key:'defects',label:'Mängel geklärt',ok:openDefects===0,detail:openDefects?openDefects+' offen':'Keine offenen Mängel'},
{key:'photos',label:'Fotodokumentation vorhanden',ok:photos>0,detail:photos?photos+' Fotos':'Noch keine Baustellenfotos'},
{key:'reports',label:'Tagesdokumentation vorhanden',ok:reports>0,detail:reports?reports+' Tagesberichte':'Noch kein Tagesbericht'},
{key:'measurement',label:'Aufmaß dokumentiert',ok:measurements>0,detail:measurements?measurements+' Aufmaße':'Noch kein Aufmaß'},
{key:'changes',label:'Nachträge geklärt',ok:draftChanges===0,detail:draftChanges?draftChanges+' Entwürfe offen':'Keine offenen Entwürfe'},
{key:'acceptance',label:'Abnahme abgeschlossen',ok:acceptanceDone,detail:acceptanceDone?'Abnahme mit Unterschrift vorhanden':'Abnahme/Unterschrift noch offen'}];
const ready=items.every(x=>x.ok);return{ready,items,open:items.filter(x=>!x.ok).length,status:ready?'Bereit zum Projektabschluss':items.filter(x=>!x.ok).length+' Punkte offen'};}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function open(project){if(!project||typeof global.openModal!=='function')return false;const c=check(project);global.openModal('<div class="modalHead"><div><div class="modalTitle">Projektabschluss prüfen</div><div class="pageSub">'+esc(project.name||'Projekt')+' · '+esc(c.status)+'</div></div><button class="iconBtn" onclick="closeModal()">×</button></div><div class="projectCloseoutStatus '+(c.ready?'isReady':'needsWork')+'"><strong>'+(c.ready?'✓ Abschlussbereit':'! Noch nicht abschlussbereit')+'</strong><span>'+(c.ready?'Alle Kernpunkte sind dokumentiert.':'Vor dem Abschluss sollten die offenen Punkte geklärt werden.')+'</span></div><div class="projectCloseoutList">'+c.items.map(x=>'<div class="projectCloseoutItem '+(x.ok?'ok':'open')+'"><span class="projectCloseoutMark">'+(x.ok?'✓':'!')+'</span><div><strong>'+esc(x.label)+'</strong><div class="pageSub">'+esc(x.detail)+'</div></div></div>').join('')+'</div><div class="modalFoot"><button class="btn" onclick="closeModal()">Schließen</button><button id="pcGoAcceptance" class="btn primary">Zur Abnahme</button></div>');global.document.getElementById('pcGoAcceptance')?.addEventListener('click',()=>{global.closeModal?.();if(typeof global.goTo==='function')global.goTo('#projekte/'+encodeURIComponent(project.id)+'/abnahme');else global.location.hash='#projekte/'+encodeURIComponent(project.id)+'/abnahme';});return true;}
return{check,open};});
